displayName=Leechfin Brainrot
author=Servanis
description=Makes Leechfin Fishing fun in silly ways
tags=fishing,skilling,leechfin,brainrot
version=
plugins=com.leechfinbrainrot.LeechfinBrainrotPlugin
build=standard